### ISSUE TITLE
How to preview in local development?

### ISSUE THREAD

**Issue by vikasbhalla05** [devwhodevs/blank-shopify-theme#1]

**Comment by devwhodevs** [comment]
Current repository just represents the folder/files structure and might be outdated. It doesn't include Shopify CLI.

Since Shopify CLI for themes slightly updated since last change in this repo, you might need to work with
Shopify CLI for themes directly instead of this repo.

https://shopify.dev/docs/api/shopify-cli/theme

Please follow official documentation
